[theme]
primaryColor = "#667eea"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true

[logger]
level = "info"

[server]
headless = true
port = 8501
runOnSave = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[deprecation]
showPyplotGlobalUse = false
